module.exports = [
  { name: 'Business', code: '6000' },
  { name: 'Weather', code: '6001' },
  { name: 'Utilities', code: '6002' },
  { name: 'Travel', code: '6003' },
  { name: 'Sports', code: '6004' },
  { name: 'Social Networking', code: '6005' },
  { name: 'Reference', code: '6006' },
  { name: 'Productivity', code: '6007' },
  { name: 'Photo & Video', code: '6008' },
  { name: 'News', code: '6009' },
  { name: 'Navigation', code: '6010' },
  { name: 'Music', code: '6011' },
  { name: 'Lifestyle', code: '6012' },
  { name: 'Health & Fitness', code: '6013' },
  { name: 'Game', code: '6014' },
  { name: 'Finance', code: '6015' },
  { name: 'Entertainment', code: '6016' },
  { name: 'Education', code: '6017' },
  { name: 'Book', code: '6018' },
  { name: 'Medical', code: '6020' },
  { name: 'Magazines & Newspapers', code: '6021' },
  { name: 'Food & Drink', code: '6023' },
  { name: 'Shopping', code: '6024' },
  { name: 'Kids', code: '6061' }
]
